// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1478231838);    // assets\Cut-09-09.png
LV_IMG_DECLARE(ui_img_98644310);    // assets\air quality project-03.png
LV_IMG_DECLARE(ui_img_11_png);    // assets\11.png
LV_IMG_DECLARE(ui_img_98642260);    // assets\air quality project-01.png
LV_IMG_DECLARE(ui_img_98636887);    // assets\air quality project-02.png
LV_IMG_DECLARE(ui_img_98647633);    // assets\air quality project-04.png
LV_IMG_DECLARE(ui_img_98646608);    // assets\air quality project-05.png
LV_IMG_DECLARE(ui_img_98641235);    // assets\air quality project-06.png
LV_IMG_DECLARE(ui_img_98648658);    // assets\air quality project-07.png
LV_IMG_DECLARE(ui_img_98651997);    // assets\air quality project-08.png
LV_IMG_DECLARE(ui_img_1986391116);    // assets\Cut-09.png

LV_FONT_DECLARE(ui_font_tong);
LV_FONT_DECLARE(ui_font_tong2);
LV_FONT_DECLARE(ui_font_tong3);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
